spring:
  jersey:
    type: filter
    
holon:
  jersey:
    forwardOn404: true
    
  jwt:
    signature-algorithm: HS256
    sharedkey-base64: eWGZLlCrUjtBZwxgzcLPnA
    expire-hours: 1
    issuer: example-issuer
    
server:
  port: 9999
  
example:
  authz:
    paths:
      /api/protected: "ROLE1"
      /api/user: "ROLE2"
      /api/details: "ROLE2"
